### ISSUE TITLE
Feature request. Title and description fields in metadata

### ISSUE THREAD

**Issue by pbencze** [nais/kafkarator#1]
Background: Datakatalogen indexes Kafka topics. In order to support search and provide information information about topics it would would be helpful if developers are encouraged to provide a title and description when creating topics

Example of topic view in datakatalogen: https://data.adeo.no/kafka/aapen-person-pdl-dokument-v1-value

**Comment by erlingjd** [comment]
@pbencze Could you please detail which fields are mandatory, or are they all optional? Does the example of topic view in datakatalogen show all available fields?

**Comment by pbencze** [comment]
mandatory, recommend & optional props can be found here: https://github.com/navikt/data-catalog-dcat-validator/blob/master/src/data_catalog_dcat_validator/models/dcat_resource.py

**Comment by ambientsound** [comment]
Documentation pushed to https://doc.nais.io.
