### ISSUE TITLE
Tildel utvikler tilgang basert på team

### ISSUE THREAD

**Issue by hakonph** [nais/kafkarator#11]
Hadde vert fin og kunne tildele utvikler tilgang til toppics basert på team.
Da er det ett sted mindre og huske og legge til / fjerne tilganger

**Comment by ybelMekk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Utvikler tilgang basert på team](https://trello.com/c/JkCrCzth/114-utvikler-tilgang-basert-p%C3%A5-team)

**Comment by mortenlj** [comment]
Jeg tror dette behovet egentlig er løst, litt sånn indirekte gjennom nais cli og det at det er team-tilhørighet som avgjør om du kan redigere Topic ressursen for å gi tilganger.

Lukker dette issuet, men kan gjerne gjenåpnes hvis du opplever at behovet ikke er dekket. Ta da gjerne med en litt mer utfyllende beskrivelse av hva du ønsker å oppnå som ikke er mulig slik det er i dag.
