### ISSUE TITLE
Application user not member of nav-infrastructure

### ISSUE THREAD

**Issue by mortenlj** [nais/kafkarator#280]
In nav-dev-gcp and nav-prod-gcp, kafkarator has an application user with only access to that Aiven project, but kafkarator in those clusters also need access to the nav-infrastructure project.

Figure out how to grant an application user access to multiple projects (this might be useful elsewhere too).

**Comment by Kyrremann** [comment]
Burde holde å legge `kafkarator` til i lista på toppen her: https://github.com/nais/nais-terraform-modules/blob/main/tenants/nav/aiven.tf

Må bare finne en måte å skille mellom dev og prod.

**Comment by mortenlj** [comment]
For å få gjennom noen endringer i nav-infrastructure har jeg manuelt opprettet en gruppe (`kafkarator-prod`), og gitt denne `service:data:write` tilgang i nav-infrastructure prosjektet. Dette bør nok ryddes vekk (evt. opprettes med terraform) når vi løser dette skikkelig.
