### ISSUE TITLE
Manage Schema Registry ACLs

### ISSUE THREAD

**Issue by mortenlj** [nais/kafkarator#63]
Aiven has introduced ACLs for Schema Registry. Previously there were no ACLs with regards to Schema Registry, but now it is possible to set ACLs that limits the users to specific subjects.

It's unclear exactly how it's best to use these, but experience from mtpilot indicates that at some point in the future the current way, where default is full access, will shift to default no access.

We should add Schema Registry ACLs when we create Topic ACLs, and manage them as a whole.

**Comment by tronghn** [comment]
According to [Aiven docs on Schema Registry Authorization](https://docs.aiven.io/docs/products/kafka/karapace/concepts/schema-registry-authorization.html):

> Karapace schema registry authorization is [enabled](https://docs.aiven.io/docs/products/kafka/karapace/howto/enable-karapace.html) on all Aiven for Apache Kafka® services. The exception is older services created before mid-2022, where the feature needs to be enabled.

The enable-link quoted only points to instructions to enable/disable Karapace, and the Aiven Console doesn't show any options to enable/disable the authorization itself. I did however find this page that describes how to do so with the Aiven CLI: https://docs.aiven.io/docs/products/kafka/karapace/howto/enable-schema-registry-authorization.html

**Comment by mortenlj** [comment]
Go client support for Kafka Schema Registry ACLs were commited to master a couple months ago, but no new release has been made.

We either need them to cut a new release, or use master.

I have created an issue about cutting a new release: https://github.com/aiven/aiven-go-client/issues/209

**Comment by mortenlj** [comment]
In order to accommodate the immediate need, I have created wildcard ACLs using terraform. Leaving this issue in the backlog so we can circle back and do a proper implementation when a new release of the go client is available.

**Comment by mortenlj** [comment]
Implemented reconciliation of schema registry ACLs, but before we can enable ACLs, all topics needs to be re-synced to generate all ACLs.

**Comment by mortenlj** [comment]
When attempting to generate all ACLs in nav-dev, we hit a limit of max 6000 ACLs (topic+schema registry) for a Kafka cluster, and Aiven says this limit can't be changed. Rolled back our changes and need to look for another way.

Possible strategy:
- Everyone gets read by default (1 rule)
- When a topic is created in a namespace, give all apps in that namespace write access to all topics in that namespace (1 rule per namespace)
- When a topic defines a producer that is not in the same namespace as the topic it produces to, give that app write access to that topic (??? rules)

This isn't perfect, but still more strict than our current policy of everyone can write everywhere, and possibly within the confines of max 6000 rules.
